docker_builder:
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  build_script: |
            git clone https://github.com/andyshinn/docker-alpine-abuild
            cd docker-alpine-abuild
            docker buildx build --platform linux/arm64,linux/amd64 -t ljfranklin/alpine-abuild:latest --push .
