name: Ubuntu Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          docker buildx create --name multibuilder
          docker buildx use multibuilder
          docker buildx inspect --bootstrap
          git clone https://github.com/andyshinn/docker-alpine-abuild
          cd docker-alpine-abuild
          docker buildx build --platform linux/arm64,linux/amd64 -t ljfranklin/alpine-abuild:latest 
          
       




